In [1]:
import pandas as pd
import numpy as np

In [2]:
customers = pd.read_csv(r"C:\Users\user\Downloads\archive (1)\Import Data\Customer.csv")
delivery = pd.read_csv(r"C:\Users\user\Downloads\archive (1)\Import Data\Delivery.csv")
orders = pd.read_csv(r"C:\Users\user\Downloads\archive (1)\Import Data\Orders.csv")
products = pd.read_csv(r"C:\Users\user\Downloads\archive (1)\Import Data\Products.csv")
rating = pd.read_csv(r"C:\Users\user\Downloads\archive (1)\Import Data\Ratings.csv")
refund = pd.read_csv(r"C:\Users\user\Downloads\archive (1)\Import Data\Returns_refund.csv")
transactions = pd.read_csv(r"C:\Users\user\Downloads\archive (1)\Import Data\Transactions.csv")

In [3]:
customers.head()

,C_ID,C_Name,Gender,Age,City,State,Street Address,Mobile
0,CS_11000001,Manbir Lala,Male,67,Delhi,Delhi,"Park Ave, 163 , Delhi , Delhi - 529675",9607971039
1,CS_11000002,Radhika More,Female,51,Pune,Maharashtra,"Elm St, 960 , Pune , Maharashtra - 328062",9109249091
2,CS_11000003,Faqid Halder,Female,57,Bengaluru,Karnataka,"Maple St, 71 , Bengaluru , Karnataka - 574209",9129509047
3,CS_11000004,Chandresh Dugar,Female,26,Thane,Maharashtra,"2nd St, 557 , Thane , Maharashtra - 329555",9351639395
4,CS_11000005,Logan Soni,Male,24,Ghaziabad,Uttar Pradesh,"Pine St, 758 , Ghaziabad , Uttar Pradesh - 119526",9445754174

In [4]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10184 entries, 0 to 10183
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   C_ID            10184 non-null  object
 1   C_Name          10184 non-null  object
 2   Gender          10184 non-null  object
 3   Age             10184 non-null  int64
 4   City            10184 non-null  object
 5   State           10184 non-null  object
 6   Street Address  10184 non-null  object
 7   Mobile          10184 non-null  int64
dtypes: int64(2), object(6)
memory usage: 636.6+ KB

In [5]:
customers.shape

(10184, 8)

In [6]:
customers.describe()

                Age        Mobile
count  10184.000000  1.018400e+04
mean      44.028476  9.504410e+09
std       15.321004  2.911076e+08
min       18.000000  9.000042e+09
25%       31.000000  9.251060e+09
50%       44.000000  9.508321e+09
75%       57.000000  9.757783e+09
max       70.000000  9.999973e+09

In [7]:
customers.isnull().sum()

C_ID              0
C_Name            0
Gender            0
Age               0
City              0
State             0
Street Address    0
Mobile            0
dtype: int64

In [8]:
customers.duplicated().sum()

np.int64(184)

In [9]:
customers.drop_duplicates(inplace = True)

In [10]:
customers.duplicated().sum()

np.int64(0)

In [11]:
delivery.head()

         DP_ID       DP_name  DP_Ratings  Percent_Cut
0  DV_61000001     Delhivery        4.52           25
1  DV_61000002  Ecom Express        3.66           20
2  DV_61000003     Blue Dart        4.32           25
3  DV_61000004    Xpressbees        4.34           20
4  DV_61000005     Shadowfax        3.45           15

In [12]:
delivery.shape

(5, 4)

In [13]:
delivery.describe()

       DP_Ratings  Percent_Cut
count    5.000000       5.0000
mean     4.058000      21.0000
std      0.471614       4.1833
min      3.450000      15.0000
25%      3.660000      20.0000
50%      4.320000      20.0000
75%      4.340000      25.0000
max      4.520000      25.0000

In [14]:
delivery.isnull().sum()

DP_ID          0
DP_name        0
DP_Ratings     0
Percent_Cut    0
dtype: int64

In [15]:
delivery.duplicated().sum()

np.int64(0)

In [16]:
orders.head()

,Or_ID,C_ID,P_ID,Order_Date,Order_Time,Qty,Coupon,DP_ID,Discount
0,OR_31000001,CS_11005317,PD_21001301,27-02-2024,22:02:00,1,NaN,DV_61000001,NaN
1,OR_31000002,CS_11000423,PD_21003593,21-01-2024,08:33:31,5,PULL,DV_61000002,25.0
2,OR_31000003,CS_11001042,PD_21004315,22-09-2024,17:26:05,1,NaN,DV_61000002,NaN
3,OR_31000004,CS_11004079,PD_21007443,26-05-2023,03:15:48,10,AGREEMENT,DV_61000003,10.0
4,OR_31000005,CS_11009894,PD_21007621,26-10-2023,04:02:44,7,WINDOW,DV_61000001,10.0

In [17]:
orders.shape

(10000, 9)

In [18]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Or_ID       10000 non-null  object
 1   C_ID        10000 non-null  object
 2   P_ID        10000 non-null  object
 3   Order_Date  10000 non-null  object
 4   Order_Time  10000 non-null  object
 5   Qty         10000 non-null  int64
 6   Coupon      4989 non-null   object
 7   DP_ID       10000 non-null  object
 8   Discount    4983 non-null   float64
dtypes: float64(1), int64(1), object(7)
memory usage: 703.3+ KB

In [19]:
orders.describe()

                Qty     Discount
count  10000.000000  4983.000000
mean       5.513600    18.195264
std        2.882195    10.709842
min        1.000000     5.000000
25%        3.000000    10.000000
50%        6.000000    15.000000
75%        8.000000    25.000000
max       10.000000    50.000000

In [20]:
orders.isnull().sum()

Or_ID            0
C_ID             0
P_ID             0
Order_Date       0
Order_Time       0
Qty              0
Coupon        5011
DP_ID            0
Discount      5017
dtype: int64

In [21]:
orders.duplicated().sum()

np.int64(0)

In [22]:
orders["Coupon"] = orders["Coupon"].fillna("No Coupon")

In [23]:
orders["Discount"] = orders["Discount"].fillna(0)

In [24]:
orders.isnull().sum()

Or_ID         0
C_ID          0
P_ID          0
Order_Date    0
Order_Time    0
Qty           0
Coupon        0
DP_ID         0
Discount      0
dtype: int64

In [25]:
products.head()

,P_ID,P_Name,Category,Company Name,Gender,Price
0,PD_21000001,Distressed Stretch Denim Charcoal Faded Jeans,Jeans,Puma,Unisex,332.77
1,PD_21000002,Straight Leg Cotton Blend Light Blue Faded Jeans,Jeans,Gap,Men,225.24
2,PD_21000003,Single-Breasted Cashmere Gray Houndstooth Blazer,Blazer,Reebok,Unisex,371.94
3,PD_21000004,Cropped Knit Dark Green Textured Hoodie,Hoodie,Puma,Men,294.26
4,PD_21000005,Formal Silk Olive Green Solid Shirt,Shirt,Levi's,Women,71.29

In [26]:
products.shape

(10000, 6)

In [27]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   P_ID          10000 non-null  object
 1   P_Name        10000 non-null  object
 2   Category      10000 non-null  object
 3   Company Name  10000 non-null  object
 4   Gender        10000 non-null  object
 5   Price         10000 non-null  float64
dtypes: float64(1), object(5)
memory usage: 468.9+ KB

In [28]:
products.describe()

              Price
count  10000.000000
mean     252.937976
std      141.447666
min       10.000000
25%      129.810000
50%      253.630000
75%      375.542500
max      499.970000

In [29]:
products.isnull().sum()

P_ID            0
P_Name          0
Category        0
Company Name    0
Gender          0
Price           0
dtype: int64

In [30]:
products.duplicated().sum()

np.int64(0)

In [31]:
rating.head()

           R_ID        Or_ID  Prod_Rating  Delivery/Service_Rating
0  RT_101000001  OR_31009479          4.0                      5.0
1  RT_101000002  OR_31001385          2.0                      2.0
2  RT_101000003  OR_31005731          5.0                      1.0
3  RT_101000004  OR_31000188          1.0                      3.0
4  RT_101000005  OR_31005904          3.0                      1.0

In [32]:
rating.describe()

       Prod_Rating  Delivery/Service_Rating
count  9978.000000              9971.000000
mean      2.992283                 3.014141
std       1.406838                 1.411765
min       1.000000                 1.000000
25%       2.000000                 2.000000
50%       3.000000                 3.000000
75%       4.000000                 4.000000
max       5.000000                 5.000000

In [33]:
rating.shape

(10000, 4)

In [34]:
rating.isnull().sum()

R_ID                        0
Or_ID                       0
Prod_Rating                22
Delivery/Service_Rating    29
dtype: int64

In [35]:
rating.duplicated().sum()

np.int64(0)

In [36]:
rating["Prod_Rating"] = rating["Prod_Rating"].fillna(0)

In [37]:
rating["Delivery/Service_Rating"] = rating["Delivery/Service_Rating"].fillna(0)

In [38]:
rating.isnull().sum()

R_ID                       0
Or_ID                      0
Prod_Rating                0
Delivery/Service_Rating    0
dtype: int64

In [39]:
refund.head()

          RT_ID        Or_ID              Reason Return/Refund        Date
0  RR_301000001  OR_31004141  Wrong Item Shipped      Approved  08-04-2023
1  RR_301000002  OR_31008145       Late Delivery      Rejected  13-05-2024
2  RR_301000003  OR_31005212  Wrong Item Shipped      Approved  01-11-2023
3  RR_301000004  OR_31006318       Late Delivery      Rejected  16-05-2024
4  RR_301000005  OR_31007423   Defective Product      Approved  10-06-2023

In [40]:
refund.shape

(2000, 5)

In [41]:
refund.describe()

               RT_ID        Or_ID             Reason Return/Refund        Date
count           2000         2000               2000          2000        2000
unique          2000         1820                  3             2         686
top     RR_301000001  OR_31008590  Defective Product      Rejected  13-12-2023
freq               1            3                670          1031          10

In [42]:
refund.isnull().sum()

RT_ID            0
Or_ID            0
Reason           0
Return/Refund    0
Date             0
dtype: int64

In [43]:
refund.duplicated().sum()

np.int64(0)

In [44]:
transactions.head()

         Tr_ID        Or_ID Transaction_Mode Rewards
0  TR_41000001  OR_31002037           Wallet      No
1  TR_41000002  OR_31008376           Wallet     Yes
2  TR_41000003  OR_31002152              UPI      No
3  TR_41000004  OR_31009239      Credit Card     Yes
4  TR_41000005  OR_31002891       Debit Card      No

In [45]:
transactions.shape

(10000, 4)

In [46]:
transactions.isnull().sum()

Tr_ID                0
Or_ID                0
Transaction_Mode    33
Rewards              0
dtype: int64

In [47]:
transactions.duplicated().sum()

np.int64(0)

In [48]:
transactions["Transaction_Mode"] = transactions["Transaction_Mode"].fillna("UPI")

In [49]:
transactions.isnull().sum()

Tr_ID               0
Or_ID               0
Transaction_Mode    0
Rewards             0
dtype: int64

In [50]:
def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("/", "_")
    )
    return df

In [51]:
customers = clean_columns(customers)
orders = clean_columns(orders)
products = clean_columns(products)
rating = clean_columns(rating)
refund = clean_columns(refund)
transactions = clean_columns(transactions)
delivery = clean_columns(delivery)

In [52]:
customers.head()

,c_id,c_name,gender,age,city,state,street_address,mobile
0,CS_11000001,Manbir Lala,Male,67,Delhi,Delhi,"Park Ave, 163 , Delhi , Delhi - 529675",9607971039
1,CS_11000002,Radhika More,Female,51,Pune,Maharashtra,"Elm St, 960 , Pune , Maharashtra - 328062",9109249091
2,CS_11000003,Faqid Halder,Female,57,Bengaluru,Karnataka,"Maple St, 71 , Bengaluru , Karnataka - 574209",9129509047
3,CS_11000004,Chandresh Dugar,Female,26,Thane,Maharashtra,"2nd St, 557 , Thane , Maharashtra - 329555",9351639395
4,CS_11000005,Logan Soni,Male,24,Ghaziabad,Uttar Pradesh,"Pine St, 758 , Ghaziabad , Uttar Pradesh - 119526",9445754174

In [53]:
customers.rename(columns = {
    "c_id" : "customer_id",
    "c_name" : "customer_name",
}, inplace = True)

In [54]:
customers.columns

Index(['customer_id', 'customer_name', 'gender', 'age', 'city', 'state',
       'street_address', 'mobile'],
      dtype='object')

In [55]:
orders.columns

Index(['or_id', 'c_id', 'p_id', 'order_date', 'order_time', 'qty', 'coupon',
       'dp_id', 'discount'],
      dtype='object')

In [56]:
orders.head()

,or_id,c_id,p_id,order_date,order_time,qty,coupon,dp_id,discount
0,OR_31000001,CS_11005317,PD_21001301,27-02-2024,22:02:00,1,No Coupon,DV_61000001,0.0
1,OR_31000002,CS_11000423,PD_21003593,21-01-2024,08:33:31,5,PULL,DV_61000002,25.0
2,OR_31000003,CS_11001042,PD_21004315,22-09-2024,17:26:05,1,No Coupon,DV_61000002,0.0
3,OR_31000004,CS_11004079,PD_21007443,26-05-2023,03:15:48,10,AGREEMENT,DV_61000003,10.0
4,OR_31000005,CS_11009894,PD_21007621,26-10-2023,04:02:44,7,WINDOW,DV_61000001,10.0

In [57]:
orders.rename(columns = {
    "or_id" : "order_id",
    "c_id" : "customer_id",
    "p_id" : "product_id",
    "dp_id" : "delivery_partner_id"
}, inplace = True)

In [58]:
orders.columns

Index(['order_id', 'customer_id', 'product_id', 'order_date', 'order_time',
       'qty', 'coupon', 'delivery_partner_id', 'discount'],
      dtype='object')

In [59]:
products.head()

,p_id,p_name,category,company_name,gender,price
0,PD_21000001,Distressed Stretch Denim Charcoal Faded Jeans,Jeans,Puma,Unisex,332.77
1,PD_21000002,Straight Leg Cotton Blend Light Blue Faded Jeans,Jeans,Gap,Men,225.24
2,PD_21000003,Single-Breasted Cashmere Gray Houndstooth Blazer,Blazer,Reebok,Unisex,371.94
3,PD_21000004,Cropped Knit Dark Green Textured Hoodie,Hoodie,Puma,Men,294.26
4,PD_21000005,Formal Silk Olive Green Solid Shirt,Shirt,Levi's,Women,71.29

In [60]:
products.rename(columns = {
    "p_id" : "product_id",
    "p_name" : "product_name"
} , inplace = True)

In [61]:
products.columns

Index(['product_id', 'product_name', 'category', 'company_name', 'gender',
       'price'],
      dtype='object')

In [62]:
rating.head()

           r_id        or_id  prod_rating  delivery_service_rating
0  RT_101000001  OR_31009479          4.0                      5.0
1  RT_101000002  OR_31001385          2.0                      2.0
2  RT_101000003  OR_31005731          5.0                      1.0
3  RT_101000004  OR_31000188          1.0                      3.0
4  RT_101000005  OR_31005904          3.0                      1.0

In [63]:
rating.rename(columns = {
    "r_id" : "rating_id",
    "od_id" : "order_id"
} , inplace = True)

In [64]:
rating.columns

Index(['rating_id', 'or_id', 'prod_rating', 'delivery_service_rating'], dtype='object')

In [65]:
refund.head()

          rt_id        or_id              reason return_refund        date
0  RR_301000001  OR_31004141  Wrong Item Shipped      Approved  08-04-2023
1  RR_301000002  OR_31008145       Late Delivery      Rejected  13-05-2024
2  RR_301000003  OR_31005212  Wrong Item Shipped      Approved  01-11-2023
3  RR_301000004  OR_31006318       Late Delivery      Rejected  16-05-2024
4  RR_301000005  OR_31007423   Defective Product      Approved  10-06-2023

In [66]:
refund.rename(columns = {
    "rt_id" : "refund_id",
    "or_id" : "order_id"
} , inplace = True)

In [67]:
refund.columns

Index(['refund_id', 'order_id', 'reason', 'return_refund', 'date'], dtype='object')

In [68]:
transactions.columns

Index(['tr_id', 'or_id', 'transaction_mode', 'rewards'], dtype='object')

In [69]:
transactions.rename(columns = {
    "tr_id" : "transaction_id",
    "or_id" : "order_id"
} , inplace = True)

In [70]:
transactions.columns

Index(['transaction_id', 'order_id', 'transaction_mode', 'rewards'], dtype='object')

In [71]:
delivery.head()

         dp_id       dp_name  dp_ratings  percent_cut
0  DV_61000001     Delhivery        4.52           25
1  DV_61000002  Ecom Express        3.66           20
2  DV_61000003     Blue Dart        4.32           25
3  DV_61000004    Xpressbees        4.34           20
4  DV_61000005     Shadowfax        3.45           15

In [72]:
delivery.columns

Index(['dp_id', 'dp_name', 'dp_ratings', 'percent_cut'], dtype='object')

In [73]:
delivery.rename(columns = {
    "dp_id" : "delivery_partner_id",
    "dp_name" : "delivery_partner_name",
    "dp_ratings" : "delivery_partner_ratings"
} , inplace = True)

In [74]:
delivery.columns

Index(['delivery_partner_id', 'delivery_partner_name',
       'delivery_partner_ratings', 'percent_cut'],
      dtype='object')

In [75]:
customers.info()
orders.info()
products.info()
transactions.info()
rating.info()
refund.info()
delivery.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     10000 non-null  object
 1   customer_name   10000 non-null  object
 2   gender          10000 non-null  object
 3   age             10000 non-null  int64
 4   city            10000 non-null  object
 5   state           10000 non-null  object
 6   street_address  10000 non-null  object
 7   mobile          10000 non-null  int64
dtypes: int64(2), object(6)
memory usage: 703.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             10000 non-null  object
 1   customer_id          10000 non-null  object
 2   product_id           10000 non-null  object
 3   order_date           10000 non-null  object
 4   order_time           10000 non-null  object
 5   qty                  10000 non-null  int64
 6   coupon               10000 non-null  object
 7   delivery_partner_id  10000 non-null  object
 8   discount             10000 non-null  float64
dtypes: float64(1), int64(1), object(7)
memory usage: 703.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    10000 non-null  object
 1   product_name  10000 non-null  object
 2   category      10000 non-null  object
 3   company_name  10000 non-null  object
 4   gender        10000 non-null  object
 5   price         10000 non-null  float64
dtypes: float64(1), object(5)
memory usage: 468.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   order_id          10000 non-null  object
 2   transaction_mode  10000 non-null  object
 3   rewards           10000 non-null  object
dtypes: object(4)
memory usage: 312.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   rating_id                10000 non-null  object
 1   or_id                    10000 non-null  object
 2   prod_rating              10000 non-null  float64
 3   delivery_service_rating  10000 non-null  float64
dtypes: float64(2), object(2)
memory usage: 312.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   refund_id      2000 non-null   object
 1   order_id       2000 non-null   object
 2   reason         2000 non-null   object
 3   return_refund  2000 non-null   object
 4   date           2000 non-null   object
dtypes: object(5)
memory usage: 78.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   delivery_partner_id       5 non-null      object
 1   delivery_partner_name     5 non-null      object
 2   delivery_partner_ratings  5 non-null      float64
 3   percent_cut               5 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [76]:
rating.rename(columns={"or_id":"order_id"}, inplace=True)

In [77]:
rating.rename(columns={"prod_rating":"product_rating"}, inplace=True)

In [78]:
orders.rename(columns={"qty":"quantity"}, inplace=True)

In [79]:
refund.rename(columns={"date":"refund_date"}, inplace=True)

In [80]:
transactions["rewards"].unique()

array(['No', 'Yes'], dtype=object)

In [81]:
customers.to_csv(
    r"D:\Myntra data\train\customer_clean.csv",
    index=False
)
print("print successfullly")

print successfullly

In [82]:
orders.to_csv(
    r"D:\Myntra data\train\order_clean.csv",
    index=False
)
print("print successfullly")

print successfullly

In [103]:
products.to_csv(
    r"D:\Myntra data\train\products_clean.csv",
    index=False
)
print("print successfullly")

print successfullly

In [84]:
rating.to_csv(
    r"D:\Myntra data\train\rating_clean.csv",
    index=False
)
print("print successfullly")

print successfullly

In [104]:
refund.to_csv(
    r"D:\Myntra data\train\refund_clean.csv",
    index=False
)
print("print successfullly")

print successfullly

In [105]:
transactions.to_csv(
    r"D:\Myntra data\train\transactions_clean.csv",
    index=False
)
print("print successfullly")

print successfullly

In [106]:
delivery.to_csv(
    r"D:\Myntra data\train\delivery_clean.csv",
    index=False
)
print("print successfullly")

print successfullly

In [88]:
customers["customer_id"].str.len().max()
products["product_id"].str.len().max()
orders["order_id"].str.len().max()
delivery["delivery_partner_id"].str.len().max()

11

In [89]:
customers.columns

Index(['customer_id', 'customer_name', 'gender', 'age', 'city', 'state',
       'street_address', 'mobile'],
      dtype='object')

In [90]:
products.columns

Index(['product_id', 'product_name', 'category', 'company_name', 'gender',
       'price'],
      dtype='object')

In [91]:
orders.columns

Index(['order_id', 'customer_id', 'product_id', 'order_date', 'order_time',
       'quantity', 'coupon', 'delivery_partner_id', 'discount'],
      dtype='object')

In [92]:
transactions.columns

Index(['transaction_id', 'order_id', 'transaction_mode', 'rewards'], dtype='object')

In [93]:
rating.columns

Index(['rating_id', 'order_id', 'product_rating', 'delivery_service_rating'], dtype='object')

In [94]:
refund.columns

Index(['refund_id', 'order_id', 'reason', 'return_refund', 'refund_date'], dtype='object')

In [95]:
pip install oracledb

Requirement already satisfied: oracledb in c:\users\user\anaconda3\lib\site-packages (3.4.2)
Requirement already satisfied: cryptography>=3.2.1 in c:\users\user\anaconda3\lib\site-packages (from oracledb) (46.0.3)
Requirement already satisfied: typing_extensions>=4.14.0 in c:\users\user\anaconda3\lib\site-packages (from oracledb) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\user\anaconda3\lib\site-packages (from cryptography>=3.2.1->oracledb) (2.0.0)
Requirement already satisfied: pycparser in c:\users\user\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=3.2.1->oracledb) (2.23)
Note: you may need to restart the kernel to use updated packages.

In [96]:
import oracledb
import pandas as pd

In [97]:
conn = oracledb.connect(
    user="myntra",
    password="myntra",
    dsn="localhost:1521/FREEPDB1"
)

cursor = conn.cursor()

print("Connected Successfully!")

Connected Successfully!

In [98]:
customers = pd.read_csv(r"D:\Myntra data\train\customer_clean.csv")
customers.head()

,customer_id,customer_name,gender,age,city,state,street_address,mobile
0,CS_11000001,Manbir Lala,Male,67,Delhi,Delhi,"Park Ave, 163 , Delhi , Delhi - 529675",9607971039
1,CS_11000002,Radhika More,Female,51,Pune,Maharashtra,"Elm St, 960 , Pune , Maharashtra - 328062",9109249091
2,CS_11000003,Faqid Halder,Female,57,Bengaluru,Karnataka,"Maple St, 71 , Bengaluru , Karnataka - 574209",9129509047
3,CS_11000004,Chandresh Dugar,Female,26,Thane,Maharashtra,"2nd St, 557 , Thane , Maharashtra - 329555",9351639395
4,CS_11000005,Logan Soni,Male,24,Ghaziabad,Uttar Pradesh,"Pine St, 758 , Ghaziabad , Uttar Pradesh - 119526",9445754174

In [99]:
customers.columns

Index(['customer_id', 'customer_name', 'gender', 'age', 'city', 'state',
       'street_address', 'mobile'],
      dtype='object')

In [100]:
customers.shape

(10000, 8)

In [101]:
customer_data = list(customers.itertuples(index = False, name = None))

In [108]:
insert_querry = """
insert into customers (
    customer_id,
    customer_name, 
    gender,
    age,
    city, 
    state,
    street_address,
    mobile
)
values (
    :1, :2, :3, :4, :5, :6, :7, :8
) """

cursor.executemany(insert_querry, customer_data)
conn.commit()

print("Data Loaded successfully")

Data Loaded successfully

In [110]:
products = pd.read_csv(r"D:\Myntra data\train\products_clean.csv")
products.head()

,product_id,product_name,category,company_name,gender,price
0,PD_21000001,Distressed Stretch Denim Charcoal Faded Jeans,Jeans,Puma,Unisex,332.77
1,PD_21000002,Straight Leg Cotton Blend Light Blue Faded Jeans,Jeans,Gap,Men,225.24
2,PD_21000003,Single-Breasted Cashmere Gray Houndstooth Blazer,Blazer,Reebok,Unisex,371.94
3,PD_21000004,Cropped Knit Dark Green Textured Hoodie,Hoodie,Puma,Men,294.26
4,PD_21000005,Formal Silk Olive Green Solid Shirt,Shirt,Levi's,Women,71.29

In [111]:
products.columns

Index(['product_id', 'product_name', 'category', 'company_name', 'gender',
       'price'],
      dtype='object')

In [125]:
product_data = list(products.itertuples(index=False, name=None))

In [130]:
insert_querry = """
    insert into products (
    product_id,
    product_name,
    category,
    company_name,
    gender, 
    price
) 
values (
    :1, :2, :3, :4, :5, :6
) """
cursor.executemany(insert_querry, product_data)
conn.commit()

print("Data Loaded Successfully")

Data Loaded Successfully

In [131]:
delivery = pd.read_csv(r"D:\Myntra data\train\delivery_clean.csv")
delivery.head()

,delivery_partner_id,delivery_partner_name,delivery_partner_ratings,percent_cut
0,DV_61000001,Delhivery,4.52,25
1,DV_61000002,Ecom Express,3.66,20
2,DV_61000003,Blue Dart,4.32,25
3,DV_61000004,Xpressbees,4.34,20
4,DV_61000005,Shadowfax,3.45,15

In [132]:
delivery.columns

Index(['delivery_partner_id', 'delivery_partner_name',
       'delivery_partner_ratings', 'percent_cut'],
      dtype='object')

In [134]:
delivery_data = list(delivery.itertuples( index = False, name = None))

In [138]:
insert_querry = """
    insert into delivery (
    delivery_partner_id,
    delivery_partner_name,
    delivery_partner_ratings,
    percent_cut
)
values (
    :1, :2, :3, :4
) """
cursor.executemany(insert_querry, delivery_data)
conn.commit()

print("Data Loaded Successfully")

Data Loaded Successfully

In [139]:
orders.dtypes

order_id                object
customer_id             object
product_id              object
order_date              object
order_time              object
quantity                 int64
coupon                  object
delivery_partner_id     object
discount               float64
dtype: object

In [140]:
orders["order_date"] = pd.to_datetime(
    orders["order_date"],
    format="%d-%m-%Y"
)

In [141]:
orders.dtypes

order_id                       object
customer_id                    object
product_id                     object
order_date             datetime64[ns]
order_time                     object
quantity                        int64
coupon                         object
delivery_partner_id            object
discount                      float64
dtype: object

In [144]:
order_data = list(orders.itertuples( index = False, name = None))

In [146]:
insert_querry = """
    insert into orders (
    order_id,
    customer_id,
    product_id,
    order_date,
    order_time,
    quantity,
    coupon,
    delivery_partner_id,
    discount
)
values (
    :1, :2, :3, :4, :5, :6, :7, :8 , :9
) """
cursor.executemany(insert_querry, order_data)
conn.commit()

print("Data Loaded Successfully")

Data Loaded Successfully

In [148]:
transactions = pd.read_csv(r"D:\Myntra data\train\transactions_clean.csv")

transaction_data = list(transactions.itertuples(index=False, name=None))

insert_query = """
INSERT INTO transactions (
    transaction_id,
    order_id,
    transaction_mode,
    reward
)
VALUES (
    :1, :2, :3, :4
)
"""

cursor.executemany(insert_query, transaction_data)
conn.commit()

print("Transactions Loaded Successfully")

Transactions Loaded Successfully

In [150]:
ratings = pd.read_csv(r"D:\Myntra data\train\rating_clean.csv")

rating_data = list(ratings.itertuples(index=False, name=None))

insert_query = """
INSERT INTO ratings (
    rating_id,
    order_id,
    product_rating,
    delivery_service_rating
)
VALUES (
    :1, :2, :3, :4
)
"""

cursor.executemany(insert_query, rating_data)
conn.commit()

print("Ratings Loaded Successfully")

Ratings Loaded Successfully

In [170]:
refund.columns

Index(['refund_id', 'order_id', 'reason', 'return_refund', 'refund_date'], dtype='object')

In [172]:
returns = pd.read_csv(r"D:\Myntra data\train\return_clean.csv")

returns["refund_date"] = pd.to_datetime(
    returns["refund_date"],
    format="%d-%m-%Y"
)

return_data = list(returns.itertuples(index=False, name=None))

insert_query = """
INSERT INTO refund (
    refund_id,
    order_id,
    reason,
    return_refund,
    refund_date
)
VALUES (
    :1, :2, :3, :4, :5
)
"""

cursor.executemany(insert_query, return_data)
conn.commit()

print("Returns Loaded Successfully")

Returns Loaded Successfully

In [165]:
returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   refund_id      2000 non-null   object
 1   order_id       2000 non-null   object
 2   reason         2000 non-null   object
 3   return_refund  2000 non-null   object
 4   refund_date    2000 non-null   object
dtypes: object(5)
memory usage: 78.3+ KB